package com.tweetapp.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Builder
@DynamoDBTable(tableName = "Reply")
@DynamoDBDocument
@NoArgsConstructor
@AllArgsConstructor
public class Reply {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private AppUser user;

    @DynamoDBAttribute
    private String comment;

    @DynamoDBAttribute
    private String tag;

    @DynamoDBAttribute
    private LocalDateTime createdAt;
}
