package com.tweetapp.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Builder
@DynamoDBTable(tableName = "Reply")
@NoArgsConstructor
@AllArgsConstructor
public class Reply {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private AppUser user;

    private String comment;

    private String tag;

    private LocalDateTime createdAt;
}
