package com.tweetapp.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

@Data
@Builder
@DynamoDBTable(tableName = "Tweet")
@NoArgsConstructor
@AllArgsConstructor
public class Tweet {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String tweetId;

    private AppUser author;

    private String content;

    private String tag;

    private LocalDateTime createdAt;

    private Set<String> likedBy;

    private List<Reply> replies;

}
