package com.tweetapp.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

@Data
@Builder
@DynamoDBTable(tableName = "Tweet")
@NoArgsConstructor
@AllArgsConstructor
public class Tweet {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String tweetId;

    @DynamoDBAttribute
    private AppUser author;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    private String tag;

    @DynamoDBAttribute
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    private Set<String> likedBy;

    @DynamoDBAttribute
    private List<Reply> replies;

}
class DateConverter implements DynamoDBTypeConverter<String, LocalDateTime> {

    @Override
    public String convert(final LocalDateTime time) {
        return time.toString();
    }

    @Override
    public LocalDateTime unconvert(final String string) {
        return LocalDateTime.parse(string);
    }
}
